services:
  todo:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - ydb
    environment:
      - YDB_ENDPOINT=grpc://ydb:2136
      - YDB_DATABASE=/local
      - YDB_ANONYMOUS_CREDENTIALS=1
  ydb:
    image: cr.yandex/yc/yandex-docker-local-ydb:latest
    container_name: ydb-local
    ports:
      - "2135:2135"
      - "2136:2136"
      - "8765:8765"
    environment:
      - GRPC_TLS_PORT=2135 
      - GRPC_PORT=2136 
      - MON_PORT=8765
    volumes:
      - ./ydb_certs:/ydb_certs
      - ./ydb_data:/ydb_data

